# Generated by Django 2.2.5 on 2019-11-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('eid', models.CharField(max_length=300)),
                ('dept', models.CharField(max_length=300)),
            ],
        ),
    ]
