# Generated by Django 2.2.5 on 2019-11-03 14:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Life', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='id',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='dept',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='eid',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('pid', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Life.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number_of_doc', models.IntegerField()),
                ('hod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Life.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtime', models.DateTimeField(default=django.utils.timezone.now)),
                ('dname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Life.Doctor')),
                ('pname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Life.Patient')),
            ],
        ),
    ]
