# Generated by Django 2.2.5 on 2019-11-04 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Life', '0004_auto_20191104_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='designation',
            field=models.CharField(default='senior doctor', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Life.Department'),
        ),
    ]
