# Generated by Django 2.2.5 on 2019-11-04 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Life', '0005_auto_20191104_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='picture_big',
            field=models.ImageField(null=True, upload_to='department/'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Life.Department'),
        ),
    ]
