# Generated by Django 2.2.5 on 2019-11-05 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Life', '0008_auto_20191105_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='did',
        ),
        migrations.AddField(
            model_name='patient',
            name='past_record',
            field=models.TextField(default='None', max_length=300),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Life.Department'),
        ),
    ]
