# Generated by Django 2.2.5 on 2019-11-07 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Life', '0010_auto_20191105_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='picture',
            field=models.ImageField(null=True, upload_to='doctors/'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Life.Department'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='past_record',
            field=models.TextField(default='', max_length=300),
        ),
    ]
