# Generated by Django 2.2.5 on 2019-11-28 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Life', '0013_auto_20191112_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='timing',
            field=models.CharField(default='Morning', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Life.Department'),
        ),
    ]
