# Generated by Django 2.2.5 on 2019-11-29 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Life', '0017_auto_20191128_1700'),
        ('Life', '0014_auto_20191128_1727'),
    ]

    operations = [
    ]
